name: legacy_cinema
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  get_storage: ^2.1.1
  get: ^4.6.6
  form_validation: ^3.1.0+8
  jwt_decode: ^0.3.1
  image_picker: ^1.0.5
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  date_time_format: ^2.0.1
  zoom_widget: ^2.0.1
  jwt_decoder: ^2.0.1
  url_launcher: ^6.0.13
  iconsax: ^0.0.8
  blur_container: ^0.0.2
  blurrycontainer: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/
  fonts:
    - family: NotoSansKhmer
      fonts:
        - asset: assets/fonts/khmer/NotoSansKhmer-Black.ttf
        - asset: assets/fonts/khmer/NotoSansKhmer-Bold.ttf
        - asset: assets/fonts/khmer/NotoSansKhmer-ExtraBold.ttf
        - asset: assets/fonts/khmer/NotoSansKhmer-ExtraLight.ttf
        - asset: assets/fonts/khmer/NotoSansKhmer-Light.ttf
        - asset: assets/fonts/khmer/NotoSansKhmer-Medium.ttf
        - asset: assets/fonts/khmer/NotoSansKhmer-Regular.ttf
        - asset: assets/fonts/khmer/NotoSansKhmer-SemiBold.ttf
        - asset: assets/fonts/khmer/NotoSansKhmer-Thin.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/english/OpenSans-Light.ttf
        - asset: assets/fonts/english/OpenSans-Regular.ttf
        - asset: assets/fonts/english/OpenSans-Bold.ttf
        - asset: assets/fonts/english/OpenSans-SemiBold.ttf
