import 'package:get/get.dart';

class Language extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "en_US": {
          "now_showing": "Now Showing",
          "movie": "Movies",
          "ticket": "Ticket",
          "history": "Booking History",
          "account": "Account",
          "khmer": "Khmer",
          "english": "English",
          "comming_soon": "Comming soon",
          "trailer": "New Trailer",
          "info": "Info",
          "booking": "Booking",
          "cinema": "Cinemas",
          "login": "Login",
          "register": "Register",
          "logout": "Logout",
          "setting": "Setting",
          "minute": "Minutes",
          "home": "Home",
          "location": "Location",
          "more_info": "More Info",
          "username": "Username",
          "password": "Password",
          "firstname": "Firstname",
          "lastname": "Lastname",
          "email": "Email",
          "confirm_password": "Confirm Password",
          "dont_have_account": "You have no account?",
          "already_have_account": "You already have account?",
          "sign_up": "Sign Up",
          "sign_in": "Sign In",
          "choose_file": "Choose File",
          "username_cant_be_empty": "Username Can't Be Empty",
          "pay": "Pay",
          "total": "Total",
          "screen": "Screen",
          "select_seat": "Select Seat",
          "username_must_be_at_least_3_characters":
              "Username must be at least 3 characters",
          "password_is_required": "Password is Required",
        },
        "kh_KH": {
          "pay": "បង់លុយ",
          "total": "សរុប",
          "screen": "អេក្រង់",
          "select_seat": "ជ្រើស​រើស​កៅ​អី​",
          "movie": "ភាពយន្ត",
          "ticket": "សំបុត្រ",
          "history": "ប្រវត្តិនៃការកក់",
          "account": "គណនី",
          "khmer": "ភាសាខ្មែរ",
          "english": "ភាសាអង់គ្លេស",
          "comming_soon": "មកដល់ឆាប់ៗនេះ",
          "trailer": "ឈុតខ្លីៗថ្មី",
          "info": "ព័ត៌មានបន្ថែម",
          "booking": "ការកក់",
          "cinema": "រោង​ភាពយន្ដ",
          "login": "ចូល",
          "register": "ចុះឈ្មោះ",
          "logout": "ចាកចេញ",
          "setting": "ការកំណត់",
          "minute": "នាទី",
          "home": "ទំព័រដើម",
          "now_showing": "កំពុងចាក់បញ្ចាំង",
          "location": "ទីតាំង",
          "more_info": "ព័ត៌មាន​បន្ថែម",
          "username": "ឈ្មោះអ្នកប្រើប្រាស់",
          "password": "ពាក្យសម្ងាត់",
          "firstname": "ឈ្មោះដើម",
          "lastname": "នាមត្រកូល",
          "email": "អ៊ីម៉ែល",
          "confirm_password": "បញ្ចាក់ពាក្យសម្ងាត់",
          "dont_have_account": "អ្នកមិនមានគណនីទេ?",
          "already_have_account": "អ្នកមានគណនីរួចហើយ?",
          "sign_up": "ចុះឈ្មោះ",
          "sign_in": "ចូលគណនី",
          "choose_file": "ជ្រើសរើសឯកសារ",
          "username_cant_be_empty": "​ឈ្មោះអ្នកប្រើប្រាស់មិនគួរទរទេរ",
          "username_must_be_at_least_3_characters":
              "ឈ្មោះ​អ្នក​ប្រើប្រាស់​គួរ​តែ​មាន​​៣អក្សរឡើង",
          "password_is_required": "ទៀមទារពាក្យសម្ងាត់",
          "now_showing_movie": "ឥឡូវនេះកំពុងបញ្ចាំងភាពយន្ត",
        }
      };
}
