import 'package:get/get.dart';

class Language extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "en_US": {
          "movie": "Movies",
          "ticket": "Ticket",
          "history": "Booking History",
          "account": "Account",
          "khmer": "Khmer",
          "english": "English",
          "comming_soon": "Comming soon",
          "trailer": "New Trailer",
          "info": "Info",
          "booking": "Booking",
          "cinema": "Cinema",
          "login": "Login",
          "register": "Register",
          "logout": "Logout",
          "setting": "Setting",
          "minute": "Minutes",
          "home": "Home",
          "now_showing": "Now Showing",
          "location": "Location",
          "more_info": "More Info",
          "username": "Username",
          "password": "Password",
          "firstname": "Firstname",
          "lastname": "Lastname",
          "email": "Email",
          "confirm_password": "Confirm Password",
          "dont_have_account": "You have no account?",
          "already_have_account": "You already have account?",
          "sign_up": "Sign Up",
          "sign_in": "Sign In",
          "choose_file": "Choose File",
        },
        "kh_KH": {
          "movie": "ភាពយន្ត",
          "ticket": "សំបុត្រ",
          "history": "ប្រវត្តិនៃការកក់",
          "account": "គណនី",
          "khmer": "ភាសាខ្មែរ",
          "english": "ភាសាអង់គ្លេស",
          "comming_soon": "មកដល់ឆាប់ៗនេះ",
          "trailer": "ឈុតខ្លីៗថ្មី",
          "info": "ព័ត៌មានបន្ថែម",
          "booking": "ការកក់",
          "cinema": "រោងភាពយន្ដ",
          "login": "ចូល",
          "register": "ចុះឈ្មោះ",
          "logout": "ចាកចេញ",
          "setting": "ការកំណត់",
          "minute": "នាទី",
          "home": "ទំព័រដើម",
          "now_showing": "កំពុងចាក់បញ្ចាំង",
          "location": "ទីតាំង",
          "more_info": "ព័ត៌មានបន្ថែម",
          "username": "ឈ្មោះអ្នកប្រើប្រាស់",
          "password": "ពាក្យសម្ងាត់",
          "firstname": "ឈ្មោះដើម",
          "lastname": "នាមត្រកូល",
          "email": "អ៊ីម៉ែល",
          "confirm_password": "បញ្ចាក់ពាក្យសម្ងាត់",
          "dont_have_account": "អ្នកមិនមានគណនីទេ?",
          "already_have_account": "អ្នកមានគណនីរួចហើយ?",
          "sign_up": "ចុះឈ្មោះ",
          "sign_in": "ចូលគណនី",
          "choose_file": "ជ្រើសរើសឯកសារ",
        }
      };
}
